'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class categoria
    Public Property id_categoria As Integer
    Public Property nombre As String
    Public Property estado As String

    Public Overridable Property productoes As ICollection(Of producto) = New HashSet(Of producto)

End Class
