'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class producto
    Public Property id_producto As Integer
    Public Property producto1 As String
    Public Property precio As Nullable(Of Decimal)
    Public Property id_categoria As Nullable(Of Integer)
    Public Property estado As String

    Public Overridable Property categoria As categoria

End Class
